### ISSUE TITLE
turn every member li into a link to it's portfolio

### ISSUE THREAD

**Issue by ACristOliv** [sorocabacss/sorocabacss.github.io#4]

**Comment by felipebernardes** [comment]
I've included my portfolio. What about yours, folks? @SonOfABeast @felipesoares6 @amandavilela @anaagabriel

**Comment by ACristOliv** [comment]
Mine's not ready yet. I'll try to finish it until the end of the next week.

**Comment by felipebernardes** [comment]
hey @SonOfABeast ! you could just link to your codepen profile until you have finished your own portfolio. What do you think?

**Comment by ACristOliv** [comment]
Ok then! Here it is: https://codepen.io/Son_of_a_Beast/full/jAYLrV/

**Comment by felipebernardes** [comment]
@SonOfABeast don't be lazy! do it yourself, brother. hahahah

**Comment by ACristOliv** [comment]
HAHAHAHA Done!

**Comment by felipebernardes** [comment]
great! :+1:

**Comment by caferrari** [comment]
my portfolio is my github account =P
